[pytest]
pythonpath = .
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*

addopts =
    -ra
    -q
    --cov=src
    --cov=app
    --cov-report=term-missing
    --cov-report=html

filterwarnings =
    ignore::DeprecationWarning